import { NextApiRequest, NextApiResponse } from "next";

const matchesData = [
  {
    id: "1",
    homeTeam: "Chelsea",
    awayTeam: "Man Utd",
    homeScore: 1,
    awayScore: 1,
    status: "live" as const,
    league: "Premier League",
    homeLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/0i2_A1PMGHflrIe3umGD2A_96x96.png",
    awayLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/udQ6ns69i-jBs_RxASrasQ_96x96.png",
    matchTime: 62,
    stadium: "Stamford Bridge",
    matchWeek: "Week 10",
    featured: true,
    homeTeamData: {
      manager: "Graham Potter",
      formation: "4-3-3",
      lineup: [
        { name: "Kepa Arrizabalaga", number: 1 },
        { name: "Reece James", number: 24 },
        { name: "Thiago Silva", number: 6 },
        { name: "Kalidou Koulibaly", number: 26 },
        { name: "Ben Chilwell", number: 21 },
        { name: "Enzo Fernandez", number: 5 },
        { name: "Mateo Kovacic", number: 8 },
        { name: "Mason Mount", number: 19 },
        { name: "Kai Havertz", number: 29 },
        { name: "Raheem Sterling", number: 17 },
        { name: "Pierre-Emerick Aubameyang", number: 9 },
      ],
      substitutes: [
        { name: "Edouard Mendy", number: 16 },
        { name: "Cesar Azpilicueta", number: 28 },
        { name: "Jorginho", number: 23 },
        { name: "Christian Pulisic", number: 10 },
        { name: "Hakim Ziyech", number: 22 },
        { name: "Conor Gallagher", number: 30 },
        { name: "Armando Broja", number: 18 },
      ],
    },
    awayTeamData: {
      manager: "E. ten Hag",
      formation: "4-2-3-1",
      lineup: [
        { name: "David de Gea", number: 1 },
        { name: "Diogo Dalot", number: 20 },
        { name: "Raphael Varane", number: 19 },
        { name: "Lisandro Martinez", number: 6 },
        { name: "Luke Shaw", number: 23 },
        { name: "Casemiro", number: 18 },
        { name: "Christian Eriksen", number: 14 },
        { name: "Antony", number: 21 },
        { name: "Bruno Fernandes", number: 8 },
        { name: "Jadon Sancho", number: 25 },
        { name: "Marcus Rashford", number: 10 },
      ],
      substitutes: [
        { name: "Tom Heaton", number: 22 },
        { name: "Harry Maguire", number: 5 },
        { name: "Fred", number: 17 },
        { name: "Scott McTominay", number: 39 },
        { name: "Anthony Martial", number: 9 },
        { name: "Alejandro Garnacho", number: 49 },
        { name: "Facundo Pellistri", number: 28 },
      ],
    }
  },
  {
    id: "2",
    homeTeam: "N Forest",
    awayTeam: "Liverpool",
    homeScore: 0,
    awayScore: 3,
    status: "live" as const,
    homeLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/nS_WGF9ydyPZPUjJpkP21A_96x96.png",
    awayLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/0iHbx-InIB_Rbb3v0pS2JQ_96x96.png",
  },
  {
    id: "3",
    homeTeam: "Man City",
    awayTeam: "Brighton",
    homeScore: 2,
    awayScore: 1,
    status: "live" as const,
    homeLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/z44l-a0W1v5FmgP1MfYGGA_96x96.png",
    awayLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/EKIe0e-ZIphOcfQAwsuEEQ_96x96.png",
  },
  {
    id: "4",
    homeTeam: "Wolves",
    awayTeam: "Leicester",
    homeScore: 1,
    awayScore: 0,
    status: "live" as const,
    homeLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/ZW73-Q34I4FNsD25m5fO_w_96x96.png",
    awayLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/Pa3d1c13B1brruUNvVsyZQ_96x96.png",
  },
];

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json(matchesData);
}
